# Generated by Django 6.0 on 2025-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0011_alter_sound_sound"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="description",
            name="meaning",
        ),
        migrations.AddField(
            model_name="description",
            name="deep_meaning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="description",
            name="general_meaning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="description",
            name="part_of_speech",
            field=models.CharField(
                choices=[
                    ("adjectival", "adjectival"),
                    ("noun", "noun"),
                    ("verb", "verb"),
                    ("alliance", "alliance"),
                    ("adverb", "adverb"),
                    ("pronoun", "pronoun"),
                    ("other", "other"),
                    ("pretext", "pretext"),
                    ("interjection", "interjection"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="translate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="part_of_speech",
            field=models.CharField(
                choices=[
                    ("adjectival", "adjectival"),
                    ("noun", "noun"),
                    ("verb", "verb"),
                    ("alliance", "alliance"),
                    ("adverb", "adverb"),
                    ("pronoun", "pronoun"),
                    ("other", "other"),
                    ("pretext", "pretext"),
                    ("interjection", "interjection"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sound",
            name="transcription",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="rank",
            field=models.IntegerField(blank=True, default=22000, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="short_description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("example", models.CharField(max_length=500, unique=True)),
                ("translate", models.CharField(max_length=500)),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True, related_name="examples", to="word.word"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Learner",
        ),
    ]
